# Using CoInt Test on S&P500



### Imports

In [1]:
#IMPORTS
%matplotlib inline

# Imports
from clr import AddReference
AddReference("System")
AddReference("QuantConnect.Common")
AddReference("QuantConnect.Jupyter")
AddReference("QuantConnect.Indicators")

from System import *
from QuantConnect import *
from QuantConnect.Data.Market import TradeBar, QuoteBar
from QuantConnect.Jupyter import *
from QuantConnect.Indicators import *
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
import pandas as pd

# Create an instance
qb = QuantBook()

### Stationarity 

In [2]:
# Dependencies
# -*- coding: utf-8 -*-
"""

Created on Thu Aug 30 12:26:38 2012

Author: Josef Perktold
"""
'''
function jc =  c_sja(n,p)
% PURPOSE: find critical values for Johansen maximum eigenvalue statistic
% ------------------------------------------------------------
% USAGE:  jc = c_sja(n,p)
% where:    n = dimension of the VAR system
%           p = order of time polynomial in the null-hypothesis
%                 p = -1, no deterministic part
%                 p =  0, for constant term
%                 p =  1, for constant plus time-trend
%                 p >  1  returns no critical values
% ------------------------------------------------------------
% RETURNS: a (3x1) vector of percentiles for the maximum eigenvalue
%          statistic for: [90% 95% 99%]
% ------------------------------------------------------------
% NOTES: for n > 12, the function returns a (3x1) vector of zeros.
%        The values returned by the function were generated using
%        a method described in MacKinnon (1996), using his FORTRAN
%        program johdist.f
% ------------------------------------------------------------
% SEE ALSO: johansen()
% ------------------------------------------------------------
% References: MacKinnon, Haug, Michelis (1996) 'Numerical distribution
% functions of likelihood ratio tests for cointegration',
% Queen's University Institute for Economic Research Discussion paper.
% -------------------------------------------------------

% written by:
% James P. LeSage, Dept of Economics
% University of Toledo
% 2801 W. Bancroft St,
% Toledo, OH 43606
% jlesage@spatial-econometrics.com
'''

import numpy as np

ss_ejcp0 = '''\
         2.9762  4.1296  6.9406
         9.4748 11.2246 15.0923
        15.7175 17.7961 22.2519
        21.8370 24.1592 29.0609
        27.9160 30.4428 35.7359
        33.9271 36.6301 42.2333
        39.9085 42.7679 48.6606
        45.8930 48.8795 55.0335
        51.8528 54.9629 61.3449
        57.7954 61.0404 67.6415
        63.7248 67.0756 73.8856
        69.6513 73.0946 80.0937'''

ss_ejcp1 = '''\
         2.7055   3.8415   6.6349
        12.2971  14.2639  18.5200
        18.8928  21.1314  25.8650
        25.1236  27.5858  32.7172
        31.2379  33.8777  39.3693
        37.2786  40.0763  45.8662
        43.2947  46.2299  52.3069
        49.2855  52.3622  58.6634
        55.2412  58.4332  64.9960
        61.2041  64.5040  71.2525
        67.1307  70.5392  77.4877
        73.0563  76.5734  83.7105'''

ss_ejcp2 = '''\
         2.7055   3.8415   6.6349
        15.0006  17.1481  21.7465
        21.8731  24.2522  29.2631
        28.2398  30.8151  36.1930
        34.4202  37.1646  42.8612
        40.5244  43.4183  49.4095
        46.5583  49.5875  55.8171
        52.5858  55.7302  62.1741
        58.5316  61.8051  68.5030
        64.5292  67.9040  74.7434
        70.4630  73.9355  81.0678
        76.4081  79.9878  87.2395'''

ejcp0 = np.array(ss_ejcp0.split(),float).reshape(-1,3)
ejcp1 = np.array(ss_ejcp1.split(),float).reshape(-1,3)
ejcp2 = np.array(ss_ejcp2.split(),float).reshape(-1,3)

def c_sja(n, p):
    if ((p > 1) or (p < -1)):
        jc = np.zeros(3)
    elif ((n > 12) or (n < 1)):
        jc = np.zeros(3)
    elif p == -1:
        jc = ejcp0[n-1,:]
    elif p == 0:
        jc = ejcp1[n-1,:]
    elif p == 1:
        jc = ejcp2[n-1,:]

    return jc

'''
function jc = c_sjt(n,p)
% PURPOSE: find critical values for Johansen trace statistic
% ------------------------------------------------------------
% USAGE:  jc = c_sjt(n,p)
% where:    n = dimension of the VAR system
%               NOTE: routine doesn't work for n > 12
%           p = order of time polynomial in the null-hypothesis
%                 p = -1, no deterministic part
%                 p =  0, for constant term
%                 p =  1, for constant plus time-trend
%                 p >  1  returns no critical values
% ------------------------------------------------------------
% RETURNS: a (3x1) vector of percentiles for the trace
%          statistic for [90% 95% 99%]
% ------------------------------------------------------------
% NOTES: for n > 12, the function returns a (3x1) vector of zeros.
%        The values returned by the function were generated using
%        a method described in MacKinnon (1996), using his FORTRAN
%        program johdist.f
% ------------------------------------------------------------
% SEE ALSO: johansen()
% ------------------------------------------------------------
% % References: MacKinnon, Haug, Michelis (1996) 'Numerical distribution
% functions of likelihood ratio tests for cointegration',
% Queen's University Institute for Economic Research Discussion paper.
% -------------------------------------------------------

% written by:
% James P. LeSage, Dept of Economics
% University of Toledo
% 2801 W. Bancroft St,
% Toledo, OH 43606
% jlesage@spatial-econometrics.com

% these are the values from Johansen's 1995 book
% for comparison to the MacKinnon values
%jcp0 = [ 2.98   4.14   7.02
%        10.35  12.21  16.16
%        21.58  24.08  29.19
%        36.58  39.71  46.00
%        55.54  59.24  66.71
%        78.30  86.36  91.12
%       104.93 109.93 119.58
%       135.16 140.74 151.70
%       169.30 175.47 187.82
%       207.21 214.07 226.95
%       248.77 256.23 270.47
%       293.83 301.95 318.14];
%
'''


ss_tjcp0 = '''\
         2.9762   4.1296   6.9406
        10.4741  12.3212  16.3640
        21.7781  24.2761  29.5147
        37.0339  40.1749  46.5716
        56.2839  60.0627  67.6367
        79.5329  83.9383  92.7136
       106.7351 111.7797 121.7375
       137.9954 143.6691 154.7977
       173.2292 179.5199 191.8122
       212.4721 219.4051 232.8291
       255.6732 263.2603 277.9962
       302.9054 311.1288 326.9716'''


ss_tjcp1 = '''\
          2.7055   3.8415   6.6349
         13.4294  15.4943  19.9349
         27.0669  29.7961  35.4628
         44.4929  47.8545  54.6815
         65.8202  69.8189  77.8202
         91.1090  95.7542 104.9637
        120.3673 125.6185 135.9825
        153.6341 159.5290 171.0905
        190.8714 197.3772 210.0366
        232.1030 239.2468 253.2526
        277.3740 285.1402 300.2821
        326.5354 334.9795 351.2150'''

ss_tjcp2 = '''\
           2.7055   3.8415   6.6349
          16.1619  18.3985  23.1485
          32.0645  35.0116  41.0815
          51.6492  55.2459  62.5202
          75.1027  79.3422  87.7748
         102.4674 107.3429 116.9829
         133.7852 139.2780 150.0778
         169.0618 175.1584 187.1891
         208.3582 215.1268 228.2226
         251.6293 259.0267 273.3838
         298.8836 306.8988 322.4264
         350.1125 358.7190 375.3203'''

tjcp0 = np.array(ss_tjcp0.split(),float).reshape(-1,3)
tjcp1 = np.array(ss_tjcp1.split(),float).reshape(-1,3)
tjcp2 = np.array(ss_tjcp2.split(),float).reshape(-1,3)

def c_sjt(n, p):
    if ((p > 1) or (p < -1)):
        jc = np.zeros(3)
    elif ((n > 12) or (n < 1)):
        jc = np.zeros(3)
    elif p == -1:
        jc = tjcp0[n-1,:]
    elif p == 0:
        jc = tjcp1[n-1,:]
    elif p == 1:
        jc = tjcp2[n-1,:]
    else:
        raise ValueError('invalid p')

    return jc

if __name__ == '__main__':
    for p in range(-2, 3, 1):
        for n in range(12):
            print n, p
            print c_sja(n, p)
            print c_sjt(n, p)



0 -2
[ 0.  0.  0.]
[ 0.  0.  0.]
1 -2
[ 0.  0.  0.]
[ 0.  0.  0.]
2 -2
[ 0.  0.  0.]
[ 0.  0.  0.]
3 -2
[ 0.  0.  0.]
[ 0.  0.  0.]
4 -2
[ 0.  0.  0.]
[ 0.  0.  0.]
5 -2
[ 0.  0.  0.]
[ 0.  0.  0.]
6 -2
[ 0.  0.  0.]
[ 0.  0.  0.]
7 -2
[ 0.  0.  0.]
[ 0.  0.  0.]
8 -2
[ 0.  0.  0.]
[ 0.  0.  0.]
9 -2
[ 0.  0.  0.]
[ 0.  0.  0.]
10 -2
[ 0.  0.  0.]
[ 0.  0.  0.]
11 -2
[ 0.  0.  0.]
[ 0.  0.  0.]
0 -1
[ 0.  0.  0.]
[ 0.  0.  0.]
1 -1
[ 2.9762  4.1296  6.9406]
[ 2.9762  4.1296  6.9406]
2 -1
[  9.4748  11.2246  15.0923]
[ 10.4741  12.3212  16.364 ]
3 -1
[ 15.7175  17.7961  22.2519]
[ 21.7781  24.2761  29.5147]
4 -1
[ 21.837   24.1592  29.0609]
[ 37.0339  40.1749  46.5716]
5 -1
[ 27.916   30.4428  35.7359]
[ 56.2839  60.0627  67.6367]
6 -1
[ 33.9271  36.6301  42.2333]
[ 79.5329  83.9383  92.7136]
7 -1
[ 39.9085  42.7679  48.6606]
[ 106.7351  111.7797  121.7375]
8 -1
[ 45.893   48.8795  55.0335]
[ 137.9954  143.6691  154.7977]
9 -1
[ 51.8528  54.9629  61.3449]
[ 173.2292  179.5199  191.8122]

In [3]:

'''
function result = johansen(x,p,k)
% PURPOSE: perform Johansen cointegration tests
% -------------------------------------------------------
% USAGE: result = johansen(x,p,k)
% where:      x = input matrix of time-series in levels, (nobs x m)
%             p = order of time polynomial in the null-hypothesis
%                 p = -1, no deterministic part
%                 p =  0, for constant term
%                 p =  1, for constant plus time-trend
%                 p >  1, for higher order polynomial
%             k = number of lagged difference terms used when
%                 computing the estimator
% -------------------------------------------------------
% RETURNS: a results structure:
%          result.eig  = eigenvalues  (m x 1)
%          result.evec = eigenvectors (m x m), where first
%                        r columns are normalized coint vectors
%          result.lr1  = likelihood ratio trace statistic for r=0 to m-1
%                        (m x 1) vector
%          result.lr2  = maximum eigenvalue statistic for r=0 to m-1
%                        (m x 1) vector
%          result.cvt  = critical values for trace statistic
%                        (m x 3) vector [90% 95% 99%]
%          result.cvm  = critical values for max eigen value statistic
%                        (m x 3) vector [90% 95% 99%]
%          result.ind  = index of co-integrating variables ordered by
%                        size of the eigenvalues from large to small
% -------------------------------------------------------
% NOTE: c_sja(), c_sjt() provide critical values generated using
%       a method of MacKinnon (1994, 1996).
%       critical values are available for n<=12 and -1 <= p <= 1,
%       zeros are returned for other cases.
% -------------------------------------------------------
% SEE ALSO: prt_coint, a function that prints results
% -------------------------------------------------------
% References: Johansen (1988), 'Statistical Analysis of Co-integration
% vectors', Journal of Economic Dynamics and Control, 12, pp. 231-254.
% MacKinnon, Haug, Michelis (1996) 'Numerical distribution
% functions of likelihood ratio tests for cointegration',
% Queen's University Institute for Economic Research Discussion paper.
% (see also: MacKinnon's JBES 1994 article
% -------------------------------------------------------

% written by:
% James P. LeSage, Dept of Economics
% University of Toledo
% 2801 W. Bancroft St,
% Toledo, OH 43606
% jlesage@spatial-econometrics.com

% ****************************************************************
% NOTE: Adina Enache provided some bug fixes and corrections that
%       she notes below in comments. 4/10/2000
% ****************************************************************
'''

import numpy as np
from numpy import zeros, ones, flipud, log
from numpy.linalg import inv, eig, cholesky as chol
from statsmodels.regression.linear_model import OLS

#from coint_tables import c_sja, c_sjt

tdiff = np.diff

class Holder(object):
    pass

def rows(x):
    return x.shape[0]

def trimr(x, front, end):
    if end > 0:
        return x[front:-end]
    else:
        return x[front:]

import statsmodels.tsa.tsatools as tsat
mlag = tsat.lagmat

def mlag_(x, maxlag):
    '''return all lags up to maxlag
    '''
    return x[:-lag]

def lag(x, lag):
    return x[:-lag]

def detrend(y, order):
    if order == -1:
        return y
    return OLS(y, np.vander(np.linspace(-1,1,len(y)), order+1)).fit().resid

def resid(y, x):
    r = y - np.dot(x, np.dot(np.linalg.pinv(x), y))
    return r

def coint_johansen(x, p, k):

    #    % error checking on inputs
    #    if (nargin ~= 3)
    #     error('Wrong # of inputs to johansen')
    #    end
    nobs, m = x.shape

    #why this?  f is detrend transformed series, p is detrend data
    if (p > -1):
        f = 0
    else:
        f = p

    x     = detrend(x,p)
    dx    = tdiff(x,1, axis=0)
    #dx    = trimr(dx,1,0)
    z     = mlag(dx,k)#[k-1:]
    z = trimr(z,k,0)
    z     = detrend(z,f)
    dx = trimr(dx,k,0)

    dx    = detrend(dx,f)
    #r0t   = dx - z*(z\dx)
    r0t   = resid(dx, z)  #diff on lagged diffs
    #lx = trimr(lag(x,k),k,0)
    lx = lag(x,k)
    lx = trimr(lx, 1, 0)
    dx    = detrend(lx,f)
    #rkt   = dx - z*(z\dx)
    rkt   = resid(dx, z)  #level on lagged diffs
    skk   = np.dot(rkt.T, rkt) / rows(rkt)
    sk0   = np.dot(rkt.T, r0t) / rows(rkt)
    s00   = np.dot(r0t.T, r0t) / rows(r0t)
    sig   = np.dot(sk0, np.dot(inv(s00), (sk0.T)))
    tmp   = inv(skk)
    #du, au = eig(np.dot(tmp, sig))
    au, du = eig(np.dot(tmp, sig))  #au is eval, du is evec
    #orig = np.dot(tmp, sig)

    #% Normalize the eigen vectors such that (du'skk*du) = I
    temp   = inv(chol(np.dot(du.T, np.dot(skk, du))))
    dt     = np.dot(du, temp)


    #JP: the next part can be done much  easier

    #%      NOTE: At this point, the eigenvectors are aligned by column. To
    #%            physically move the column elements using the MATLAB sort,
    #%            take the transpose to put the eigenvectors across the row

    #dt = transpose(dt)

    #% sort eigenvalues and vectors

    #au, auind = np.sort(diag(au))
    auind = np.argsort(au)
    #a = flipud(au)
    aind = flipud(auind)
    a = au[aind]
    #d = dt[aind,:]
    d = dt[:,aind]

    #%NOTE: The eigenvectors have been sorted by row based on auind and moved to array "d".
    #%      Put the eigenvectors back in column format after the sort by taking the
    #%      transpose of "d". Since the eigenvectors have been physically moved, there is
    #%      no need for aind at all. To preserve existing programming, aind is reset back to
    #%      1, 2, 3, ....

    #d  =  transpose(d)
    #test = np.dot(transpose(d), np.dot(skk, d))

    #%EXPLANATION:  The MATLAB sort function sorts from low to high. The flip realigns
    #%auind to go from the largest to the smallest eigenvalue (now aind). The original procedure
    #%physically moved the rows of dt (to d) based on the alignment in aind and then used
    #%aind as a column index to address the eigenvectors from high to low. This is a double
    #%sort. If you wanted to extract the eigenvector corresponding to the largest eigenvalue by,
    #%using aind as a reference, you would get the correct eigenvector, but with sorted
    #%coefficients and, therefore, any follow-on calculation would seem to be in error.
    #%If alternative programming methods are used to evaluate the eigenvalues, e.g. Frame method
    #%followed by a root extraction on the characteristic equation, then the roots can be
    #%quickly sorted. One by one, the corresponding eigenvectors can be generated. The resultant
    #%array can be operated on using the Cholesky transformation, which enables a unit
    #%diagonalization of skk. But nowhere along the way are the coefficients within the
    #%eigenvector array ever changed. The final value of the "beta" array using either method
    #%should be the same.


    #% Compute the trace and max eigenvalue statistics */
    lr1 = zeros(m)
    lr2 = zeros(m)
    cvm = zeros((m,3))
    cvt = zeros((m,3))
    iota = ones(m)
    t, junk = rkt.shape
    for i in range(0, m):
        tmp = trimr(log(iota-a), i ,0)
        lr1[i] = -t * np.sum(tmp, 0)  #columnsum ?
        #tmp = np.log(1-a)
        #lr1[i] = -t * np.sum(tmp[i:])
        lr2[i] = -t * log(1-a[i])
        cvm[i,:] = c_sja(m-i,p)
        cvt[i,:] = c_sjt(m-i,p)
        aind[i]  = i
    #end

    result = Holder()
    #% set up results structure
    #estimation results, residuals
    result.rkt = rkt
    result.r0t = r0t
    result.eig = a
    result.evec = d  #transposed compared to matlab ?
    result.lr1 = lr1
    result.lr2 = lr2
    result.cvt = cvt
    result.cvm = cvm
    result.ind = aind
    result.meth = 'johansen'

    return result

def print_johan_stats(res):
     print 'trace statistic', res.lr1
     print 'critical vals %90,%95,%99'
     for i in range(len(res.cvt)): print 'r<=%d' % i, res.cvt[i]
     print
     print 'eigen statistic', res.lr2
     print 'critical values  %90,%95,%99'
     for i in range(len(res.cvm)): print 'r<=%d' % i, res.cvm[i]
     print
     print 'ozdegerler', res.eig
     print
     print 'ozvektorler'
     print
     print res.evec
    



In [4]:
import statsmodels.formula.api as smf
import pandas as pd
import numpy as np

def halflife(df,col):
    df['ylag'] = df[col].shift(1)
    df['deltaY'] = df[col] - df['ylag']
    results = smf.ols('deltaY ~ ylag', data=df).fit()
    lam = results.params['ylag']
    halflife=-np.log(2)/lam
    return lam, halflife


In [5]:
# Stationarity Test

def main():

    df = pd.read_csv('bitcoin_eurthum_close.csv',index_col=0)
    cols = ['ewc','ewa','ige']
    stripped_code(df, cols)
    


def stripped_code(df, cols):
    """Pass in a pandas data frame of the form:
    
    df =                ewa     ewc     ige     dwf

            8/7/2015    279.03  2.77    45.12   45.12   
            8/8/2015    260.20  0.75    46.46   46.5
            8/9/2015    x       x       x       x
    
    where cols = ['ewc','ewa','ige']
    
    """


    # from johansen import coint_johansen, print_johan_stats

    #df = pd.read_csv('bitcoin_eurthum_close.csv',index_col=0)
    #cols = ['ewc','ewa','ige']

    vals=df[cols]
    res3 = coint_johansen(vals, 0, 1)
    print_johan_stats(res3)
    df['yport'] = np.dot(vals, res3.evec[:,0])

    #import halflife
    #hf = halflife.halflife(df, 'yport')[1]
    hf = halflife(df, 'yport')[1]
    hf=int(round(hf))

    data_mean = pd.rolling_mean(df['yport'], window=hf)
    data_std = pd.rolling_std(df['yport'], window=hf)
    # yport evec ile senet carpimi
    # numUnits yport'un Z skoru
    df['numUnits'] = -1*(df['yport']-data_mean) / data_std

    # Z skoru 3 kolon yap
    tmp1 = np.ones(df[cols].shape) * np.array([df['numUnits']]).T
    # evec tekrarla, her satirda tekrar tekrar
    tmp2 = np.ones(df[cols].shape) * np.array([res3.evec[:,0]])
    # evec sermayenin nasil bolusturuldugu olarak gorulebilir
    # positions ise her senete dolar biriminde ne kadar para ayrildigi
    positions = tmp1 * tmp2 * df[cols]
    positions = pd.DataFrame(positions)
    # stratejinin gunluk kar/zarari
    pnl = positions.shift(1) * (df[cols] - df[cols].shift(1))  / df[cols].shift(1)
    pnl = pnl.sum(axis=1)
    # getiri ise pnl'in portfoyun brut piyasa degeri ile bolunmesi
    ret=pnl / np.sum(np.abs(positions.shift(1)),axis=1)
    # Kumulatif birlesik getiri


    #plt.plot(np.cumprod(1+ret)-1)
    #plt.show()
    APR = ((np.prod(1.+ret))**(252./len(ret)))-1
    Sharpe = np.sqrt(252.)*np.mean(ret)/np.std(ret)
    
    print 'APR', ((np.prod(1.+ret))**(252./len(ret)))-1
    print 'Sharpe', np.sqrt(252.)*np.mean(ret)/np.std(ret)

    return APR, Sharpe 


### Choose Equities to Test

In [6]:
#Simple one 
#aapl = qb.AddEquity('aapl')
#ge   = qb.AddEquity('ge')
#fb   = qb.AddEquity('fb')

In [7]:
# Need to do this
SandP = ['MMM', 'ABT', 'ABBV', 'ACN', 'ATVI', 'AYI', 'ADBE', 'AAP', 'AES', 'AET', 'AMG', 'AFL', 'A', 'APD', 'AKAM', 'ALK', 'ALB', 'ALXN', 'ALLE', 'AGN', 'ADS', 'LNT', 'ALL', 'GOOGL', 'GOOG', 'MO', 'AMZN', 'AEE', 'AAL', 'AEP', 'AXP', 'AIG', 'AMT', 'AWK', 'AMP', 'ABC', 'AME', 'AMGN', 'APH', 'APC', 'ADI', 'ANTM', 'AON', 'APA', 'AIV', 'AAPL', 'AMAT', 'ADM', 'ARNC', 'AJG', 'AIZ', 'T', 'ADSK', 'ADP', 'AN', 'AZO', 'AVB', 'AVY', 'BHI', 'BLL', 'BAC', 'BCR', 'BAX', 'BBT', 'BDX', 'BBBY', 'BRK.B', 'BBY', 'BIIB', 'BLK', 'HRB', 'BA', 'BWA', 'BXP', 'BSX', 'BMY', 'AVGO', 'BF.B', 'CHRW', 'CA', 'COG', 'CPB', 'COF', 'CAH', 'KMX', 'CCL', 'CAT', 'CBOE', 'CBG', 'CBS', 'CELG', 'CNC', 'CNP', 'CTL', 'CERN', 'CF', 'SCHW', 'CHTR', 'CHK', 'CVX', 'CMG', 'CB', 'CHD', 'CI', 'XEC', 'CINF', 'CTAS', 'CSCO', 'C', 'CFG', 'CTXS', 'CME', 'CMS', 'COH', 'KO', 'CTSH', 'CL', 'CMCSA', 'CMA', 'CAG', 'CXO', 'COP', 'ED', 'STZ', 'GLW', 'COST', 'COTY', 'CCI', 'CSRA', 'CSX', 'CMI', 'CVS', 'DHI', 'DHR', 'DRI', 'DVA', 'DE', 'DLPH', 'DAL', 'XRAY', 'DVN', 'DLR', 'DFS', 'DISCA', 'DISCK', 'DG', 'DLTR', 'D', 'DOV', 'DOW', 'DPS', 'DTE', 'DD', 'DUK', 'DNB', 'ETFC', 'EMN', 'ETN', 'EBAY', 'ECL', 'EIX', 'EW', 'EA', 'EMR', 'ETR', 'EVHC', 'EOG', 'EQT', 'EFX', 'EQIX', 'EQR', 'ESS', 'EL', 'ES', 'EXC', 'EXPE', 'EXPD', 'ESRX', 'EXR', 'XOM', 'FFIV', 'FB', 'FAST', 'FRT', 'FDX', 'FIS', 'FITB', 'FSLR', 'FE', 'FISV', 'FLIR', 'FLS', 'FLR', 'FMC', 'FTI', 'FL', 'F', 'FTV', 'FBHS', 'BEN', 'FCX', 'FTR', 'GPS', 'GRMN', 'GD', 'GE', 'GGP', 'GIS', 'GM', 'GPC', 'GILD', 'GPN', 'GS', 'GT', 'GWW', 'HAL', 'HBI', 'HOG', 'HAR', 'HRS', 'HIG', 'HAS', 'HCA', 'HCP', 'HP', 'HSIC', 'HES', 'HPE', 'HOLX', 'HD', 'HON', 'HRL', 'HST', 'HPQ', 'HUM', 'HBAN', 'IDXX', 'ITW', 'ILMN', 'INCY', 'IR', 'INTC', 'ICE', 'IBM', 'IP', 'IPG', 'IFF', 'INTU', 'ISRG', 'IVZ', 'IRM', 'JBHT', 'JEC', 'SJM', 'JNJ', 'JCI', 'JPM', 'JNPR', 'KSU', 'K', 'KEY', 'KMB', 'KIM', 'KMI', 'KLAC', 'KSS', 'KHC', 'KR', 'LB', 'LLL', 'LH', 'LRCX', 'LEG', 'LEN', 'LUK', 'LVLT', 'LLY', 'LNC', 'LLTC', 'LKQ', 'LMT', 'L', 'LOW', 'LYB', 'MTB', 'MAC', 'M', 'MNK', 'MRO', 'MPC', 'MAR', 'MMC', 'MLM', 'MAS', 'MA', 'MAT', 'MKC', 'MCD', 'MCK', 'MJN', 'MDT', 'MRK', 'MET', 'MTD', 'KORS', 'MCHP', 'MU', 'MSFT', 'MAA', 'MHK', 'TAP', 'MDLZ', 'MON', 'MNST', 'MCO', 'MS', 'MSI', 'MUR', 'MYL', 'NDAQ', 'NOV', 'NAVI', 'NTAP', 'NFLX', 'NWL', 'NFX', 'NEM', 'NWSA', 'NWS', 'NEE', 'NLSN', 'NKE', 'NI', 'NBL', 'JWN', 'NSC', 'NTRS', 'NOC', 'NRG', 'NUE', 'NVDA', 'ORLY', 'OXY', 'OMC', 'OKE', 'ORCL', 'PCAR', 'PH', 'PDCO', 'PAYX', 'PYPL', 'PNR', 'PBCT', 'PEP', 'PKI', 'PRGO', 'PFE', 'PCG', 'PM', 'PSX', 'PNW', 'PXD', 'PNC', 'RL', 'PPG', 'PPL', 'PX', 'PCLN', 'PFG', 'PG', 'PGR', 'PLD', 'PRU', 'PEG', 'PSA', 'PHM', 'PVH', 'QRVO', 'QCOM', 'PWR', 'DGX', 'RRC', 'RTN', 'O', 'RHT', 'REG', 'REGN', 'RF', 'RSG', 'RAI', 'RHI', 'ROK', 'COL', 'ROP', 'ROST', 'RCL', 'R', 'SPGI', 'CRM', 'SCG', 'SLB', 'SNI', 'STX', 'SEE', 'SRE', 'SHW', 'SIG', 'SPG', 'SWKS', 'SLG', 'SNA', 'SO', 'LUV', 'SWN', 'SWK', 'SPLS', 'SBUX', 'STT', 'SRCL', 'SYK', 'STI', 'SYMC', 'SYF', 'SYY', 'TROW', 'TGT', 'TEL', 'TGNA', 'TDC', 'TSO', 'TXN', 'TXT', 'BK', 'CLX', 'COO', 'HSY', 'MOS', 'TRV', 'DIS', 'TMO', 'TIF', 'TWX', 'TJX', 'TMK', 'TSS', 'TSCO', 'TDG', 'RIG', 'TRIP', 'FOXA', 'FOX', 'TSN', 'USB', 'UDR', 'ULTA', 'UA', 'UAA', 'UNP', 'UAL', 'UNH', 'UPS', 'URI', 'UTX', 'UHS', 'UNM', 'URBN', 'VFC', 'VLO', 'VAR', 'VTR', 'VRSN', 'VRSK', 'VZ', 'VRTX', 'VIAB', 'V', 'VNO', 'VMC', 'WMT', 'WBA', 'WM', 'WAT', 'WEC', 'WFC', 'HCN', 'WDC', 'WU', 'WRK', 'WY', 'WHR', 'WFM', 'WMB', 'WLTW', 'WYN', 'WYNN', 'XEL', 'XRX', 'XLNX', 'XL', 'XYL', 'YHOO', 'YUM', 'ZBH', 'ZION', 'ZTS'] 
for company in SandP:
    qb.AddEquity(company)

### Historical Data Requests


In [8]:
# Gets historical data from the subscribed assets, the last 360 datapoints with daily resolution
h1 = qb.History(360, Resolution.Daily)
h1;

In [9]:
# Access a particular equity
h1

close       high        low       open     volume
symbol time                                                             
A      2016-05-25  44.738114  44.935154  44.452404  44.452404  1598815.0
       2016-05-26  44.856338  44.925302  44.531221  44.905598  1761732.0
       2016-05-27  45.137121  45.171603  44.698705  44.876042  1123131.0
       2016-05-31  45.201160  45.319384  44.900672  45.112491  1251980.0
       2016-06-01  45.275050  45.417904  44.777522  45.033675  1219692.0
       2016-06-02  45.215938  45.467165  45.142047  45.230716  1449167.0
       2016-06-03  45.033675  45.171603  44.521369  45.053379  1706929.0
       2016-06-06  45.171603  45.329236  45.004119  45.053379  1545107.0
       2016-06-07  45.078009  45.270124  44.935154  45.132195  1104889.0
       2016-06-08  45.467165  45.496721  45.013971  45.043527   956804.0
       2016-06-09  45.408052  45.496721  45.201160  45.299680   670190.0
       2016-06-10  44.688853  45.142047  44.521369  45.073083   892111.0
       2016-06-13  44.255364  44.846486  44.235660  44.649445   912331.0
       2016-06-14  44.255364  44.279994  43.900690  44.058323  1094708.0
       2016-06-15  44.284920  44.708558  44.235660  44.442552  1199809.0
       2016-06-16  44.703632  44.747966  43.925320  44.058323  1207154.0
       2016-06-17  44.688853  44.747966  44.215956  44.747966  1838631.0
       2016-06-20  45.447461  45.664205  44.885894  44.885894  1761899.0
       2016-06-21  45.486869  45.723318  45.082935  45.723318  1008564.0
       2016-06-22  45.348940  45.782430  45.270124  45.467165  1380232.0
       2016-06-23  45.979471  45.989323  45.743022  45.811986   917666.0
       2016-06-24  43.467200  44.393292  43.260308  43.890838  2320374.0
       2016-06-27  41.654425  43.063267  41.358864  42.915486  2818093.0
       2016-06-28  42.462292  42.472144  41.536201  42.028803  2743762.0
       2016-06-29  43.112527  43.329272  42.550961  42.905634  1507480.0
       2016-06-30  43.813919  43.858375  43.092743  43.152018  1237086.0
       2016-07-01  44.070777  44.258480  43.774403  43.823799  1129251.0
       2016-07-05  43.216232  43.813919  43.102622  43.774403  1172575.0
       2016-07-06  43.942348  44.011502  42.835886  43.122381  1364034.0
       2016-07-07  43.873194  44.199205  43.645974  43.932469  1277210.0
...                      ...        ...        ...        ...        ...
ZTS    2017-09-15  65.190000  65.650000  64.870000  65.410000  1230808.0
       2017-09-18  65.230000  65.410000  64.640000  65.310000   806196.0
       2017-09-19  64.780000  65.410000  64.530000  65.170000  1124294.0
       2017-09-20  64.470000  65.080000  64.010000  64.720000  1304743.0
       2017-09-21  64.250000  64.860000  64.200000  64.500000   771203.0
       2017-09-22  64.150000  64.550000  63.940000  64.070000   936719.0
       2017-09-25  63.650000  64.340000  63.510000  64.340000  1216564.0
       2017-09-26  63.350000  64.140000  63.290000  63.710000   983077.0
       2017-09-27  63.230000  63.650000  63.020000  63.600000   999824.0
       2017-09-28  63.310000  63.730000  62.790000  63.570000  1163471.0
       2017-09-29  63.750000  63.780000  62.900000  63.450000  1150801.0
       2017-10-02  63.750000  64.390000  63.695000  64.160000   973643.0
       2017-10-03  63.590000  64.100000  63.390000  63.750000  1188095.0
       2017-10-04  63.580000  64.020000  63.520000  63.680000  1095072.0
       2017-10-05  63.750000  63.990000  63.280000  63.570000  1470803.0
       2017-10-06  63.740000  63.960000  63.580000  63.750000  1219308.0
       2017-10-09  63.700000  63.880000  63.510000  63.730000   664499.0
       2017-10-10  64.010000  64.220000  63.440000  64.220000   871421.0
       2017-10-11  64.270000  64.280000  63.790000  63.900000   783084.0
       2017-10-12  64.920000  64.935000  64.180000  64.240000  1059379.0
       2017-10-13  65.450000  65.525000  64.790000  64.930000  1499269.0
       2017-10-16  65.710000  65.800000  65.360000  65.590000  1299848.0
       2

In [10]:
def standardize(eq_list):
    df = pd.DataFrame(h1.loc[eq_list[0]]["close"])
    for eq_ind in range(1, len(eq_list)):
        df[eq_list[eq_ind]] = (h1.loc[eq_list[eq_ind]]["close"])
    df.columns = eq_list
    return df

In [11]:
def enumerate_combinations(the_list, coint):

    if(coint==0):
        return [[]]

    if(coint>len(the_list)):
        return []
        
    if(coint==len(the_list)):
        return [the_list]

    else:
        a=[]
        for i in range(len(the_list)):
            fixed_elem=the_list[i]
            combinations=enumerate_combinations(the_list[i+1:], coint-1)
            for elem in combinations:
                elem.append(fixed_elem)
            a=a+combinations
        return a

In [ ]:
comb = enumerate_combinations(SandP, 3)

### Run Stationarity

In [16]:
# Run it on one pair
stripped_code(df3, cols=['AAPL', 'GE', 'FB'])

trace statistic [ 17.864725     5.99734486   0.42086503]
critical vals %90,%95,%99
r<=0 [ 27.0669  29.7961  35.4628]
r<=1 [ 13.4294  15.4943  19.9349]
r<=2 [ 2.7055  3.8415  6.6349]

eigen statistic [ 11.86738014   5.57647983   0.42086503]
critical values  %90,%95,%99
r<=0 [ 18.8928  21.1314  25.865 ]
r<=1 [ 12.2971  14.2639  18.52  ]
r<=2 [ 2.7055  3.8415  6.6349]

ozdegerler [  2.37328930e-04   1.11527838e-04   8.41760187e-06]

ozvektorler

[[-0.09124309 -0.22682954 -0.04700537]
 [-1.29783556  0.31529355 -0.5702478 ]
 [-0.21698992  0.15219646  0.01977286]]
APR 0.00117992654803
Sharpe 0.183746685158


/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:40: FutureWarning: pd.rolling_mean is deprecated for Series and will be removed in a future version, replace with 
	Series.rolling(window=1291,center=False).mean()
/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:41: FutureWarning: pd.rolling_std is deprecated for Series and will be removed in a future version, replace with 
	Series.rolling(window=1291,center=False).std()


(0.001179926548034782, 0.18374668515777323)

In [ ]:
# Figure out how to loop it


### Extra Code

In [8]:
# Gets historical data from the subscribed assets, between two dates with daily resolution
h3 = qb.History(spy.Symbol, datetime(2014,1,1), datetime.now(), Resolution.Daily)

NameError: name 'spy' is not defined

In [9]:
# Only fetchs historical data from a desired symbol
h4 = qb.History(spy.Symbol, 360, Resolution.Daily)
# or qb.History("SPY", 360, Resolution.Daily)

NameError: name 'spy' is not defined

In [10]:
# Only fetchs historical data from a desired symbol
# When we are not dealing with equity, we must use the generic method
h5 = qb.History[QuoteBar](eur.Symbol, timedelta(30), Resolution.Daily)
# or qb.History[QuoteBar]("EURUSD", timedelta(30), Resolution.Daily)

NameError: name 'eur' is not defined